# Generated by Django 6.0 on 2026-01-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placehighlight',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
