# Generated by Django 6.0 on 2026-01-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonPlaceDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SalonPlaceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='places/highlights/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='Salon.salonplacedes')),
            ],
        ),
        migrations.CreateModel(
            name='SalonPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Salon.salonplacedes')),
            ],
        ),
        migrations.CreateModel(
            name='SalonPlaceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='salon_places/offers/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Salon.salonplacedes')),
            ],
        ),
    ]
