# Generated by Django 6.0 on 2026-01-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loungesPlaceDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='loungesPlaceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='places/highlights/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='lounges_party.loungesplacedes')),
            ],
        ),
        migrations.CreateModel(
            name='loungesPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lounges_party.loungesplacedes')),
            ],
        ),
        migrations.CreateModel(
            name='loungesPlaceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='places/offers/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='lounges_party.loungesplacedes')),
            ],
        ),
    ]
